version: '3.9'
services:
  satisfactory-dedicated-server:
    container_name: satisfactory-server
    image: wolveix/satisfactory-server:latest:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    volumes:
      - ./satisfactory-server:/config
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G:
